# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traceback_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('traceback', models.TextField(help_text='Full traceback (json)')),
                ('urls', models.TextField(help_text='List of URLs implicated (json)')),
                ('name', models.CharField(help_text='Exception text thrown (first line)', max_length=255)),
                ('description', models.TextField(help_text='Full exception text.')),
                ('started', models.DateTimeField(help_text='First time we started to see this error in the logs.')),
                ('ended', models.DateTimeField(help_text='Last time we saw this error in the logs.')),
                ('count', models.PositiveIntegerField(default=1, help_text='Number of times seem in logs.')),
                ('issue', models.URLField(blank=True, help_text='Location of the error in a bug tracker.', null=True)),
                ('fixed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-count',),
            },
        ),
        migrations.CreateModel(
            name='HeartBeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Command Name (after manage.py)', max_length=128)),
                ('user', models.CharField(db_index=True, help_text='User who ran the command.', max_length=128)),
                ('error', models.TextField(blank=True, help_text='Any error message from the process.', null=True)),
                ('started', models.DateTimeField(help_text='Date when the command was started')),
                ('ended', models.DateTimeField(blank=True, help_text='Date when the command ended', null=True)),
                ('status', models.IntegerField(default=0, help_text='Exit code of the process')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('beats', models.IntegerField(default=1, help_text='Number of times run since creation.')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='heartbeat',
            unique_together=set([('name', 'user')]),
        ),
    ]
